#!/usr/bin/python2.7
import calendar
import datetime
import json
import optparse
import sys
import time
import urllib2

# Constants {{{
DOMAIN = 'http://us.battle.net'
URL_BASE = DOMAIN + '/api/d3/profile/'

CLASSES = {
	'barbarian' : 'Barbarian',
	'crusader' : 'Crusader',
	'demon-hunter' : 'Demon Hunter',
	'monk' : 'Monk',
	'witch-doctor' : 'Witch Doctor',
	'wizard' : 'Wizard'
}

ARTISANS = {
	'blacksmith' : 'Blacksmith',
	'jeweler' : 'Jeweler',
	'mystic' : 'Mystic'
}

STATS = {
	'strength' : 'Strength',
	'dexterity' : 'Dexterity',
	'intelligence' : 'Intelligence',
	'vitality' : 'Vitality',
	'life' : 'Life',
	'armor' : 'Armor',
	'damage' : 'DPS',
	'toughness' : 'Toughness',
	'healing' : 'Healing',
	'attackSpeed' : 'Attack speed',
	'damageIncrease' : 'Damage increase',
	'critDamage' : 'Crit damage',
	'critChance' : 'Crit chance',
	'physicalResist' : 'Resist physical',
	'fireResist' : 'Resist fire',
	'coldResist' : 'Resist cold',
	'lightningResist' : 'Resist lightning',
	'poisonResist' : 'Resist poison',
	'arcaneResist' : 'Resist arcane',
	'blockChance' : 'Block chance',
	'blockAmountMin' : 'Block amount (min)',
	'blockAmountMax' : 'Block amount (max)',
	'thorns' : 'Damage returned per hit',
	'lifeSteal' : 'Life steal',
	'lifePerKill' : 'Life per kill',
	'lifeOnHit' : 'Life per hit',
	'goldFind' : 'Gold find',
	'magicFind' : 'Magic find'
}

FOLLOWERS = {
	'enchantress' : 'Enchantress',
	'scoundrel' : 'Scoundrel',
	'templar' : 'Templar'
}

FOLLOWER_STATS = {
	'goldfind' : 'Gold Find',
	'magicfind' : 'Magic Find',
	'experience' : 'Experience'
}
# }}}

# CLEVERLY NAMED function to retrieve a remote URL
def curl(url, data = None): # {{{
	req = urllib2.Request(url)

	if(data != None):
		req.add_data(urllib.urlencode(data))

	try:
		handle = urllib2.urlopen(req)
	except IOError, e:
		return ''
	
	data = handle.read()
	return data 
# }}}

# Warning: This will loop forever if curl or json.loads() keeps throwing exceptions
def curlJson(url, data = None): # {{{
	jsonSuccess = False
	failCount = 0
	while(failCount < 5 and not jsonSuccess):
		try:
			daters = json.loads(curl(url, data))
			jsonSuccess = True
		except:
			#print 'derped. herping again'
			failCount = failCount + 1
			jsonSuccess = False
	if(failCount >= 5):
		sys.exit(2)
	return daters
# }}}

def get_highest_level(heroes, classname): # {{{
	highest_level = 0
	for hero in [hero for hero in heroes if hero['class'] == classname]:
		if(hero['level'] > highest_level):
			highest_level = hero['level']
	return None if highest_level == 0 else highest_level
# }}}
		
# Parse command-line arguments {{{
cmdline = optparse.OptionParser(usage = 'usage: %prog profile-name')
cmdline.add_option('-j', '--json', action = 'store_true', dest = 'json', default = False, help = 'Output pretty JSON instead of SevOne-consumable text')

(options, args) = cmdline.parse_args()
if(len(args) != 1):
	cmdline.print_help()
	sys.exit(1)

(profile_name,) = args
# }}}

timestamp = str(int(calendar.timegm(datetime.datetime.utcnow().timetuple())))
# Go out and grab all our data from the API {{{
profile_url = URL_BASE + profile_name + '/'

heroes_remote = {}
account_data_remote = curlJson(profile_url)
for hero in account_data_remote['heroes']:
	heroes_remote[hero['id']] = curlJson(profile_url + 'hero/' + str(hero['id']))
# }}}

# Scrub it and make the data structures with just stuff we care about {{{
heroes = {}
account_data = {
	'name' : account_data_remote['battleTag'],
	'acts_beaten' : account_data_remote['progression'].values().count(True),
	'elite_kills' : account_data_remote['kills']['elites'],
	'lifetime_kills' : account_data_remote['kills']['monsters'],
	'paragon_level' : account_data_remote['paragonLevel']
}
for key in CLASSES.iterkeys():
	account_data['highest_level_' + key] = get_highest_level(account_data_remote['heroes'], key)
	account_data['percent_time_' + key] = int(100 * account_data_remote['timePlayed'][key])
for key in ARTISANS.iterkeys():
	account_data[key + '_normal'] = account_data_remote[key]['level']
	account_data[key + '_hardcore'] = account_data_remote[key + 'Hardcore']['level']

for hero in heroes_remote.values():
	hero_entry = {
		'name' : hero['name'],
		'class' : CLASSES[hero['class']],
		'level' : hero['level'],
		'paragon_level' : hero['paragonLevel'],
		'elite_kills' : hero['kills']['elites'],
		'resources' : [
			{
				'cur' : hero['stats']['primaryResource'],
				'max' : hero['stats']['primaryResource']
			},
			{
				'cur' : None if hero['stats']['secondaryResource'] == 0 else hero['stats']['secondaryResource'],
				'max' : None if hero['stats']['secondaryResource'] == 0 else hero['stats']['secondaryResource'],
			}
		]
	}
	for key in STATS.iterkeys():
		hero_entry[key] = hero['stats'][key]
	for key in FOLLOWERS.iterkeys():
		hero_entry['follower_' + key + '_experience'] = 0 if not key in hero['followers'].keys() else hero['followers'][key]['stats']['experienceBonus']
		hero_entry['follower_' + key + '_goldfind'] = 0 if not key in hero['followers'].keys() else hero['followers'][key]['stats']['goldFind']
		hero_entry['follower_' + key + '_magicfind'] = 0 if not key in hero['followers'].keys() else hero['followers'][key]['stats']['magicFind']
	heroes[hero['id']] = hero_entry
# }}}

# Output! {{{
if(options.json):
	print json.dumps({'account_data' : account_data, 'heroes' : heroes}, sort_keys = True, indent = 4)
else:
	sys.stdout.write(timestamp + ' "Account: ' + account_data['name'] + '" "Diablo III account" "Career stats"')
	sys.stdout.write(' "Acts complete" GAUGE Number ' + str(account_data['acts_beaten']))
	sys.stdout.write(' "Kills" GAUGE Kills ' + str(account_data['lifetime_kills']))
	sys.stdout.write(' "Kills /sec" COUNTER64 Kills ' + str(account_data['lifetime_kills']))
	sys.stdout.write(' "Elite kills" GAUGE Kills ' + str(account_data['elite_kills']))
	sys.stdout.write(' "Elite kills /sec" COUNTER64 Kills ' + str(account_data['elite_kills']))
	for (key, label) in CLASSES.iteritems():
		sys.stdout.write(' "Time spent playing ' + label + '" GAUGE Percent ' + str(account_data['percent_time_' + key]))
		sys.stdout.write(' "Highest level ' + label + '" GAUGE Level ' + str(account_data['highest_level_' + key]))
	for (key, label) in ARTISANS.iteritems():
		sys.stdout.write(' "' + label + ' level on Normal" GAUGE Level ' + str(account_data[key + '_normal']))
		sys.stdout.write(' "' + label + ' level on Hardcore" GAUGE Level ' + str(account_data[key + '_hardcore']))
	sys.stdout.write("\n")

	for (hero_id, hero) in heroes.iteritems():
		sys.stdout.write(timestamp + ' "Hero: ' + hero['name'] + ' (#' + str(hero_id) + ')" "Diablo III hero" "' + hero['class'] + '"')
		sys.stdout.write(' "Level" GAUGE Level ' + str(hero['level']))
		for (key, label) in STATS.iteritems():
			sys.stdout.write(' "' + label + '" GAUGE Number ' + str(hero[key]))
		for i in xrange(0, len(hero['resources'])):
			sys.stdout.write(' "Resource ' + str(i) + ' current" GAUGE Number ' + str(hero['resources'][i]['cur']))
			sys.stdout.write(' "Resource ' + str(i) + ' maximum" GAUGE Number ' + str(hero['resources'][i]['max']))
		for (key, label) in FOLLOWERS.iteritems():
			for (stat_key, stat_label) in FOLLOWER_STATS.iteritems():
				sys.stdout.write(' "' + label + ' ' + stat_label + '" GAUGE Number ' + str(hero['follower_' + key + '_' + stat_key]))
		sys.stdout.write(' "Elite kills" GAUGE Kills ' + str(hero['elite_kills']))
		sys.stdout.write(' "Elite kills /sec" COUNTER64 Kills ' + str(hero['elite_kills']))
		sys.stdout.write("\n")
		
# }}}

